//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeChatORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AliDB_dbEntities : DbContext
    {
        public AliDB_dbEntities()
            : base("name=AliDB_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaiDuAccessToken> BaiDuAccessToken { get; set; }
        public DbSet<Company> Company { get; set; }
        public DbSet<WeChatSetting> WeChatSetting { get; set; }
    }
}
