//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeChatORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class JokeDetail
    {
        public int Id { get; set; }
        public int FormId { get; set; }
        public string Author { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string Content { get; set; }
        public string ImgUrl { get; set; }
        public string Tag { get; set; }
        public int GoodNum { get; set; }
        public int ReplyNum { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
